# ============================================================
#  social-topic-miner  ·  Full Flow Test (Colab)
#
#  Follows the "Simplified Flow" diagram:
#
#  API (following feed)
#    └─► Section 1  (Clustering + Post Ranking)
#          ├─► Feed & For You tab  ← direct
#          └─► Section 2A  (Keyword / Query Generation)
#                └─► API (Search Content, K queries × Q posts)
#                      └─► Combined feed + search posts
#                             └─► Section 3  (Cut-off)
#                                   ├─► Balanced tab  ─► Section 1 again
#                                   └─► Other tab
# ============================================================

# ──────────────────────────────────────────────────────────────
# CELL 1 ─ Install
# ──────────────────────────────────────────────────────────────
# Run this cell first, then restart the runtime before continuing.

# !pip install "git+https://github.com/Chelsea-hzc/Capstone-Data.git@test" -q
# !pip install bertopic umap-learn hdbscan sentence-transformers -q


# ──────────────────────────────────────────────────────────────
# CELL 2 ─ Flow parameters  (tune these to match your product)
# ──────────────────────────────────────────────────────────────

# ── Diagram variables ─────────────────────────────────────────
A = 4          # max topics to surface from Section 1
S = 5          # representative posts shown per topic in the Feed tab
K = 5          # search queries generated by Section 2A (one per stance)
Q = 6          # posts returned per search query (simulated here)

# ── Section 3 thresholds ──────────────────────────────────────
BALANCED_THRESHOLD  = 0.40   # score >= this  →  Balanced tab  (default)
MIN_DIVERSITY_SCORE = 0.28   # score <  this  →  dropped entirely  (default)


# ──────────────────────────────────────────────────────────────
# CELL 3 ─ Generate fake "Following" timeline posts  (N posts)
#          Replace this with your real API data.
# ──────────────────────────────────────────────────────────────

from datetime import datetime, timezone, timedelta

def _ts(hours_ago: float) -> str:
    """ISO-8601 timestamp N hours in the past."""
    dt = datetime.now(timezone.utc) - timedelta(hours=hours_ago)
    return dt.strftime("%Y-%m-%dT%H:%M:%S.000Z")

# Four clear topics, 20 posts each → N = 80 following posts.
# Each post has ≥ 8 words (preprocessing default).

FOLLOWING_POSTS = [

    # ── Topic 1: AI Safety ────────────────────────────────────
    {"text": "OpenAI has quietly reduced the size of its safety research team this quarter", "platform": "twitter", "created_at": _ts(1),  "like_count": 4200, "reply_count": 890,  "retweet_count": 1100},
    {"text": "Sam Altman says safety and rapid deployment are not mutually exclusive goals", "platform": "twitter", "created_at": _ts(2),  "like_count": 3100, "reply_count": 750,  "retweet_count": 890},
    {"text": "Anthropic releases new safety evaluation benchmarks for large language models", "platform": "twitter", "created_at": _ts(2),  "like_count": 2800, "reply_count": 400,  "retweet_count": 700},
    {"text": "AI safety researchers warn about risks of accelerating model deployment timelines", "platform": "reddit", "created_at": _ts(3),  "like_count": 1900, "reply_count": 310,  "retweet_count": 500, "ups": 1900, "num_comments": 310},
    {"text": "DeepMind publishes alignment research showing progress on AI goal specification", "platform": "twitter", "created_at": _ts(3),  "like_count": 2100, "reply_count": 280,  "retweet_count": 620},
    {"text": "Former OpenAI safety lead criticizes the pace of GPT-5 model deployment publicly", "platform": "twitter", "created_at": _ts(4),  "like_count": 5500, "reply_count": 1200, "retweet_count": 2100},
    {"text": "New EU AI Act requires safety audits before deploying large foundation models commercially", "platform": "reddit", "created_at": _ts(4),  "like_count": 1400, "reply_count": 200,  "retweet_count": 400, "ups": 1400, "num_comments": 200},
    {"text": "OpenAI board reinstates safety committee following employee pressure and public backlash", "platform": "twitter", "created_at": _ts(5),  "like_count": 3800, "reply_count": 660,  "retweet_count": 1400},
    {"text": "Tech executives debate whether AI safety concerns are slowing down innovation unnecessarily", "platform": "twitter", "created_at": _ts(5),  "like_count": 2300, "reply_count": 510,  "retweet_count": 800},
    {"text": "Researchers demonstrate new red-teaming technique to find safety issues in LLMs faster", "platform": "reddit", "created_at": _ts(6),  "like_count": 900,  "reply_count": 120,  "retweet_count": 300, "ups": 900, "num_comments": 120},
    {"text": "Google DeepMind safety team doubles in size ahead of Gemini Ultra model release", "platform": "twitter", "created_at": _ts(6),  "like_count": 2700, "reply_count": 380,  "retweet_count": 750},
    {"text": "AI alignment startup raises funding to develop better oversight tools for language models", "platform": "twitter", "created_at": _ts(7),  "like_count": 1600, "reply_count": 200,  "retweet_count": 430},
    {"text": "Congressional hearing on AI safety focuses on deployment risks and accountability gaps", "platform": "twitter", "created_at": _ts(7),  "like_count": 3200, "reply_count": 590,  "retweet_count": 1100},
    {"text": "Model cards and safety evals are now required by major cloud providers before API access", "platform": "reddit", "created_at": _ts(8),  "like_count": 1100, "reply_count": 150,  "retweet_count": 320, "ups": 1100, "num_comments": 150},
    {"text": "OpenAI and Meta disagree publicly on open-source versus closed safety approaches for AI", "platform": "twitter", "created_at": _ts(8),  "like_count": 4100, "reply_count": 900,  "retweet_count": 1600},
    {"text": "Safety researchers propose new framework for evaluating catastrophic risk in AI systems", "platform": "twitter", "created_at": _ts(9),  "like_count": 1800, "reply_count": 250,  "retweet_count": 520},
    {"text": "AI labs are hiring ethicists and safety engineers at record pace this year globally", "platform": "twitter", "created_at": _ts(10), "like_count": 2200, "reply_count": 300,  "retweet_count": 600},
    {"text": "Leaked document reveals internal debate at major AI lab about acceptable safety tradeoffs", "platform": "reddit", "created_at": _ts(10), "like_count": 6800, "reply_count": 1500, "retweet_count": 3200, "ups": 6800, "num_comments": 1500},
    {"text": "AI safety institute publishes first annual report on frontier model risk assessments", "platform": "twitter", "created_at": _ts(11), "like_count": 1500, "reply_count": 190,  "retweet_count": 410},
    {"text": "Pressure to compete with rivals is causing safety teams to be sidelined says whistleblower", "platform": "twitter", "created_at": _ts(12), "like_count": 7200, "reply_count": 1800, "retweet_count": 3900},

    # ── Topic 2: NBA / Sports ─────────────────────────────────
    {"text": "LeBron James scores 38 points to lead the Lakers past the Warriors in overtime thriller", "platform": "twitter", "created_at": _ts(1),  "like_count": 28000, "reply_count": 3200, "retweet_count": 8100},
    {"text": "Stephen Curry breaks his own three-point record in a dominant performance against Boston", "platform": "twitter", "created_at": _ts(2),  "like_count": 32000, "reply_count": 4100, "retweet_count": 10200},
    {"text": "NBA playoffs bracket predictions are shaking up after surprising first-round upsets tonight", "platform": "reddit", "created_at": _ts(2),  "like_count": 5400, "reply_count": 890, "retweet_count": 1200, "ups": 5400, "num_comments": 890},
    {"text": "Nikola Jokic wins third MVP award as Denver Nuggets clinch top seed in Western Conference", "platform": "twitter", "created_at": _ts(3),  "like_count": 19000, "reply_count": 2800, "retweet_count": 6500},
    {"text": "Warriors announce new roster changes heading into the final stretch of regular season play", "platform": "twitter", "created_at": _ts(3),  "like_count": 12000, "reply_count": 1600, "retweet_count": 3800},
    {"text": "Celtics defense holds opponents to franchise low scoring in fifth consecutive home victory", "platform": "twitter", "created_at": _ts(4),  "like_count": 9800,  "reply_count": 1100, "retweet_count": 2700},
    {"text": "Rookie sensation Victor Wembanyama drops 42 points including eight blocks in a historic game", "platform": "twitter", "created_at": _ts(4),  "like_count": 41000, "reply_count": 5600, "retweet_count": 14000},
    {"text": "NBA commissioner discusses expanding the league to new markets including Las Vegas and Seattle", "platform": "reddit", "created_at": _ts(5),  "like_count": 3200, "reply_count": 620, "retweet_count": 900, "ups": 3200, "num_comments": 620},
    {"text": "Bucks struggle without Giannis as injury concerns mount ahead of Eastern Conference playoffs", "platform": "twitter", "created_at": _ts(5),  "like_count": 11000, "reply_count": 1400, "retweet_count": 3200},
    {"text": "Heat culture continues to develop young talent despite losing veteran players in free agency", "platform": "twitter", "created_at": _ts(6),  "like_count": 7600,  "reply_count": 880,  "retweet_count": 2100},
    {"text": "Knicks fans pack Madison Square Garden as team surges toward first playoff berth in years", "platform": "twitter", "created_at": _ts(6),  "like_count": 15000, "reply_count": 2100, "retweet_count": 4800},
    {"text": "Lakers versus Warriors rivalry game draws highest TV ratings of the NBA regular season so far", "platform": "reddit", "created_at": _ts(7),  "like_count": 4100, "reply_count": 700, "retweet_count": 1100, "ups": 4100, "num_comments": 700},
    {"text": "Trade deadline moves reshape Western Conference title race with several blockbuster deals announced", "platform": "twitter", "created_at": _ts(7),  "like_count": 22000, "reply_count": 3400, "retweet_count": 7800},
    {"text": "Phoenix Suns fire head coach after disappointing stretch despite Kevin Durant playing well", "platform": "twitter", "created_at": _ts(8),  "like_count": 18000, "reply_count": 2900, "retweet_count": 6200},
    {"text": "All-Star weekend voting opens as fans rally to get their favorite underdog players selected", "platform": "twitter", "created_at": _ts(8),  "like_count": 9100,  "reply_count": 1300, "retweet_count": 2600},
    {"text": "76ers Joel Embiid cleared to return after missing twelve games with knee injury concern", "platform": "reddit", "created_at": _ts(9),  "like_count": 8800, "reply_count": 1200, "retweet_count": 2400, "ups": 8800, "num_comments": 1200},
    {"text": "Clippers versus Mavericks matchup delivers instant classic with four overtime periods played", "platform": "twitter", "created_at": _ts(9),  "like_count": 26000, "reply_count": 3800, "retweet_count": 9100},
    {"text": "NBA G League prospects drawing interest from top teams as draft season approaches this spring", "platform": "twitter", "created_at": _ts(10), "like_count": 4200,  "reply_count": 580,  "retweet_count": 1100},
    {"text": "Playoff seeding comes down to final week as six teams within two games of each other in East", "platform": "reddit", "created_at": _ts(10), "like_count": 6300, "reply_count": 950, "retweet_count": 1800, "ups": 6300, "num_comments": 950},
    {"text": "Lakers announce LeBron James will not be re-signed sending shockwaves through the entire league", "platform": "twitter", "created_at": _ts(11), "like_count": 89000, "reply_count": 14000, "retweet_count": 38000},

    # ── Topic 3: Climate & Energy ─────────────────────────────
    {"text": "New IPCC report warns of irreversible climate tipping points if emissions are not cut urgently", "platform": "twitter", "created_at": _ts(1),  "like_count": 8100,  "reply_count": 1200, "retweet_count": 3400},
    {"text": "Solar panel installations break global record for the third consecutive year according to IEA data", "platform": "twitter", "created_at": _ts(2),  "like_count": 6200,  "reply_count": 810,  "retweet_count": 2100},
    {"text": "Biden administration announces largest ever investment in offshore wind energy infrastructure", "platform": "reddit", "created_at": _ts(2),  "like_count": 4800, "reply_count": 720, "retweet_count": 1600, "ups": 4800, "num_comments": 720},
    {"text": "Carbon capture technology reaches cost parity with fossil fuel energy production says new study", "platform": "twitter", "created_at": _ts(3),  "like_count": 3900,  "reply_count": 510,  "retweet_count": 1300},
    {"text": "Flooding in Southeast Asia displaces millions as scientists link event directly to climate change", "platform": "twitter", "created_at": _ts(3),  "like_count": 11000, "reply_count": 1800, "retweet_count": 4200},
    {"text": "EU carbon tax border adjustment mechanism begins phase-in affecting global trade flows significantly", "platform": "reddit", "created_at": _ts(4),  "like_count": 2900, "reply_count": 380, "retweet_count": 950, "ups": 2900, "num_comments": 380},
    {"text": "Electric vehicle sales surpass gasoline cars for first time in Norway Germany and Netherlands markets", "platform": "twitter", "created_at": _ts(4),  "like_count": 7400,  "reply_count": 990,  "retweet_count": 2600},
    {"text": "Glacier retreat in Himalayas threatens fresh water supply for over one billion people downstream", "platform": "twitter", "created_at": _ts(5),  "like_count": 9200,  "reply_count": 1400, "retweet_count": 3800},
    {"text": "Nuclear energy renaissance gains momentum as countries revisit plant closures to meet climate targets", "platform": "twitter", "created_at": _ts(5),  "like_count": 5600,  "reply_count": 880,  "retweet_count": 1900},
    {"text": "Methane emissions from agriculture sector far exceed official government estimates new satellite data shows", "platform": "reddit", "created_at": _ts(6),  "like_count": 3400, "reply_count": 450, "retweet_count": 1100, "ups": 3400, "num_comments": 450},
    {"text": "Wildfire season starts weeks earlier than average across California Oregon and British Columbia this year", "platform": "twitter", "created_at": _ts(6),  "like_count": 6800,  "reply_count": 920,  "retweet_count": 2300},
    {"text": "Green hydrogen production costs falling rapidly as electrolyzer technology improves significantly worldwide", "platform": "twitter", "created_at": _ts(7),  "like_count": 4100,  "reply_count": 520,  "retweet_count": 1400},
    {"text": "Climate activists block oil pipeline construction site causing delays and drawing national media attention", "platform": "reddit", "created_at": _ts(7),  "like_count": 5200, "reply_count": 780, "retweet_count": 1700, "ups": 5200, "num_comments": 780},
    {"text": "Record ocean temperatures threaten coral reef ecosystems across the Great Barrier Reef this summer", "platform": "twitter", "created_at": _ts(8),  "like_count": 7800,  "reply_count": 1100, "retweet_count": 3100},
    {"text": "Energy transition requires massive investment in grid infrastructure says International Energy Agency", "platform": "twitter", "created_at": _ts(8),  "like_count": 3700,  "reply_count": 460,  "retweet_count": 1200},
    {"text": "Arctic sea ice reaches new record low extent raising alarm among climate scientists globally", "platform": "twitter", "created_at": _ts(9),  "like_count": 8900,  "reply_count": 1300, "retweet_count": 3600},
    {"text": "Countries failing to meet Paris Agreement targets as fossil fuel subsidies hit new record highs", "platform": "reddit", "created_at": _ts(9),  "like_count": 6100, "reply_count": 880, "retweet_count": 2100, "ups": 6100, "num_comments": 880},
    {"text": "Battery storage technology breakthrough could make renewable energy dispatchable around the clock", "platform": "twitter", "created_at": _ts(10), "like_count": 5300,  "reply_count": 700,  "retweet_count": 1800},
    {"text": "COP30 negotiations stall as developing nations demand more funding from wealthy countries for adaptation", "platform": "twitter", "created_at": _ts(10), "like_count": 4400,  "reply_count": 600,  "retweet_count": 1500},
    {"text": "Extreme heat kills hundreds as cities across Europe and Asia set new temperature records this week", "platform": "twitter", "created_at": _ts(11), "like_count": 12000, "reply_count": 2100, "retweet_count": 5200},

    # ── Topic 4: Music / Entertainment ───────────────────────
    {"text": "Taylor Swift Eras Tour becomes highest-grossing concert tour in music history by wide margin", "platform": "twitter", "created_at": _ts(1),  "like_count": 95000, "reply_count": 12000, "retweet_count": 42000},
    {"text": "Beyonce Renaissance World Tour sells out stadiums across four continents within minutes of opening", "platform": "twitter", "created_at": _ts(2),  "like_count": 78000, "reply_count": 9800,  "retweet_count": 34000},
    {"text": "Grammy nominations announced with several surprising snubs causing controversy among music fans online", "platform": "reddit", "created_at": _ts(2),  "like_count": 18000, "reply_count": 2800, "retweet_count": 7400, "ups": 18000, "num_comments": 2800},
    {"text": "Sabrina Carpenter new album debut breaks streaming records across Spotify Apple Music and YouTube", "platform": "twitter", "created_at": _ts(3),  "like_count": 31000, "reply_count": 4200,  "retweet_count": 12000},
    {"text": "Coachella lineup reveals headliners for both weekends with several iconic reunion performances announced", "platform": "twitter", "created_at": _ts(3),  "like_count": 44000, "reply_count": 6100,  "retweet_count": 18000},
    {"text": "Drake and Kendrick Lamar beef reaches new heights with dueling diss tracks released overnight", "platform": "twitter", "created_at": _ts(4),  "like_count": 120000,"reply_count": 18000, "retweet_count": 56000},
    {"text": "Billie Eilish wins Album of the Year Grammy becoming youngest artist to win twice in category", "platform": "reddit", "created_at": _ts(4),  "like_count": 29000, "reply_count": 3800, "retweet_count": 11000, "ups": 29000, "num_comments": 3800},
    {"text": "Streaming numbers show vinyl record sales highest since 1987 as physical music makes surprising comeback", "platform": "twitter", "created_at": _ts(5),  "like_count": 15000, "reply_count": 2100,  "retweet_count": 5800},
    {"text": "Morgan Wallen country album crossover success continues breaking records on pop charts worldwide", "platform": "twitter", "created_at": _ts(5),  "like_count": 22000, "reply_count": 3100,  "retweet_count": 8400},
    {"text": "Music festival season kicks off with massive crowds and record ticket prices causing fan frustration", "platform": "reddit", "created_at": _ts(6),  "like_count": 8900, "reply_count": 1400, "retweet_count": 3100, "ups": 8900, "num_comments": 1400},
    {"text": "SZA completes sold-out world tour after postponing dates for health reasons earlier this year", "platform": "twitter", "created_at": _ts(6),  "like_count": 18000, "reply_count": 2400,  "retweet_count": 6800},
    {"text": "Olivia Rodrigo second album GUTS maintains chart dominance six months after original release date", "platform": "twitter", "created_at": _ts(7),  "like_count": 26000, "reply_count": 3600,  "retweet_count": 9800},
    {"text": "Post Malone country music pivot surprises fans as debut single tops both country and pop charts", "platform": "reddit", "created_at": _ts(7),  "like_count": 34000, "reply_count": 4900, "retweet_count": 13000, "ups": 34000, "num_comments": 4900},
    {"text": "Record labels struggle with AI-generated music flooding streaming platforms with fake artist profiles", "platform": "twitter", "created_at": _ts(8),  "like_count": 11000, "reply_count": 1800,  "retweet_count": 4200},
    {"text": "Concert ticket resale market faces new regulation as lawmakers target predatory scalping practices", "platform": "twitter", "created_at": _ts(8),  "like_count": 9400,  "reply_count": 1500,  "retweet_count": 3600},
    {"text": "K-pop group BTS members return from military service setting off global celebration from fanbase", "platform": "reddit", "created_at": _ts(9),  "like_count": 67000, "reply_count": 8900, "retweet_count": 28000, "ups": 67000, "num_comments": 8900},
    {"text": "Spotify announces layoffs while simultaneously reporting record subscriber growth and revenue numbers", "platform": "twitter", "created_at": _ts(9),  "like_count": 14000, "reply_count": 2200,  "retweet_count": 5400},
    {"text": "Independent artists earn more from touring than streaming as per-stream rates remain controversially low", "platform": "twitter", "created_at": _ts(10), "like_count": 7800,  "reply_count": 1200,  "retweet_count": 3100},
    {"text": "Music awards show ratings hit new all-time low as fans prefer social media reaction content instead", "platform": "reddit", "created_at": _ts(10), "like_count": 6200, "reply_count": 980, "retweet_count": 2400, "ups": 6200, "num_comments": 980},
    {"text": "Taylor Swift announces surprise album drop after ending Eras Tour sending internet into full meltdown", "platform": "twitter", "created_at": _ts(11), "like_count": 890000,"reply_count": 95000, "retweet_count": 420000},
]

print(f"✓  Following posts ready:  N = {len(FOLLOWING_POSTS)}")


# ──────────────────────────────────────────────────────────────
# CELL 4 ─ Build the API with small-dataset–friendly config
#           (BERTopic needs smaller min_cluster_size for < 200 posts)
# ──────────────────────────────────────────────────────────────

from social_topic_miner import TopicMinerAPI, TopicMinerConfig
from social_topic_miner.config import (
    ClusteringConfig, HDBSCANConfig, UMAPConfig,
    SelectionConfig, SamplingConfig, PreprocessingConfig,
    PartitionConfig,
)
from social_topic_miner.diversity.filter import DiversityFilterConfig

config = TopicMinerConfig(
    preprocessing=PreprocessingConfig(min_word_count=6),   # relaxed for synthetic data
    clustering=ClusteringConfig(
        umap=UMAPConfig(n_neighbors=5, n_components=5),
        hdbscan=HDBSCANConfig(min_cluster_size=4, min_samples=2),
        min_topic_size=4,
    ),
    selection=SelectionConfig(top_n_topics=A),
    partition=PartitionConfig(min_k=2, max_k=4),
    sampling=SamplingConfig(
        recency_window_hours=48,
        target_min=S,
        target_max=S + 3,
    ),
)
diversity_config = DiversityFilterConfig(
    balanced_threshold=BALANCED_THRESHOLD,
    min_diversity_score=MIN_DIVERSITY_SCORE,
    max_posts_out=30,
)

# ── Optional: add a real summarizer ──────────────────────────
# from social_topic_miner.summarizers import OpenAISummarizer, AnthropicSummarizer
# summarizer = OpenAISummarizer(api_key="sk-...")
# summarizer = AnthropicSummarizer(api_key="...")
summarizer = None   # skip LLM summarization for this test run

api = TopicMinerAPI(config=config, summarizer=summarizer, diversity_config=diversity_config)
print("✓  TopicMinerAPI ready")


# ──────────────────────────────────────────────────────────────
# CELL 5 ─ SECTION 1  ·  Clustering + Post Representative Ranking
#           (diagram: "Section 1A + 1B")
# ──────────────────────────────────────────────────────────────

print("\n" + "═" * 60)
print("  SECTION 1  ─  Clustering + Post Ranking")
print("═" * 60)

s1 = api.section1(FOLLOWING_POSTS)

print(f"\n  Posts processed : {s1['total_posts_processed']}")
print(f"  Topics found    : {len(s1['topics'])}")
if s1["digest"]:
    print(f"\n  ── Digest ──────────────────────────────────────────────")
    print(f"  {s1['digest']}")

print(f"\n  ── Topics (Feed & For You tab) ─────────────────────────")
for t in s1["topics"]:
    print(f"\n  Topic {t['topic_id']}  [{t['category']}]")
    print(f"  Headline      : {t['headline'] or '(no summarizer)'}")
    print(f"  Short summary : {t['short_summary'] or '(no summarizer)'}")
    print(f"  Keywords      : {', '.join(t['keywords'][:6])}")
    print(f"  Posts in cluster: {t['n_posts']}   Perspectives: {t['n_perspectives']}")
    print(f"  Representative posts ({len(t['representative_posts'])}):")
    for rp in t["representative_posts"][:S]:
        print(f"    [{rp['platform']:7s}] {rp['text'][:75]}")


# ──────────────────────────────────────────────────────────────
# CELL 6 ─ SECTION 2A  ·  Keyword / Query Generation  (per topic)
#           (diagram: "Section 2A: Key Word dressing separately")
#           Input: one TopicOut at a time from Section 1
#           Output: K ranked search queries for that topic
# ──────────────────────────────────────────────────────────────

print("\n" + "═" * 60)
print("  SECTION 2A  ─  Search Query Generation  (per topic)")
print("═" * 60)

# Generate queries for EACH topic independently (single-topic call).
# In production: execute each topic's queries before moving to the next.
all_s2_queries = []
for t in s1["topics"]:
    s2_topic = api.section2({"topic": t})   # ← single topic
    all_s2_queries.extend(s2_topic["queries"])
    print(f"\n  Topic {t['topic_id']} [{t['category']}]  ({len(s2_topic['queries'])} queries)")
    for q in s2_topic["queries"][:2]:
        print(f"    prob={q['probability']:.2f}  [{q['metadata'].get('stance',''):10s}]  {q['query_string'][:70]}")

# Also show the flat batch view sorted by probability
s2 = api.section2({"topics": s1["topics"]})   # batch — all topics
print(f"\n  ── All queries flat (sorted by probability) ─────────────")
print(f"  Total: {len(s2['queries'])} queries across {len(s1['topics'])} topics")
print(f"\n  Top {K} (highest probability first):")
for i, q in enumerate(s2["queries"][:K], 1):
    print(f"  #{i}  prob={q['probability']:.2f}  topic={q['source_topic_id']}  [{q['metadata'].get('stance',''):10s}]  {q['query_string'][:65]}")


# ──────────────────────────────────────────────────────────────
# CELL 7 ─ Simulate Search Content  (K queries × Q posts each)
#           In production: send s2["queries"] to Twitter / Reddit API.
#           Here we generate fake diverse perspectives.
# ──────────────────────────────────────────────────────────────

SIMULATED_SEARCH_RESULTS = [

    # ── Diverse / opposing AI safety views ───────────────────
    {"text": "The panic around AI safety is overblown and is slowing down beneficial technology progress", "platform": "twitter", "created_at": _ts(1), "like_count": 2100, "reply_count": 480, "retweet_count": 650},
    {"text": "AI safety concerns are a marketing tactic used by incumbents to block open-source competition", "platform": "reddit", "created_at": _ts(2), "like_count": 1800, "reply_count": 390, "retweet_count": 510, "ups": 1800, "num_comments": 390},
    {"text": "We need urgent international treaties to govern AI development before it is too late for society", "platform": "twitter", "created_at": _ts(1), "like_count": 5200, "reply_count": 910, "retweet_count": 1900},
    {"text": "Small AI labs cannot afford the safety overhead that big tech companies propose as industry standard", "platform": "twitter", "created_at": _ts(3), "like_count": 1400, "reply_count": 280, "retweet_count": 420},
    {"text": "Independent safety audits are the only way to hold AI companies accountable for their model releases", "platform": "reddit", "created_at": _ts(2), "like_count": 3100, "reply_count": 550, "retweet_count": 1000, "ups": 3100, "num_comments": 550},
    {"text": "AI systems already cause harm through bias and misuse yet we only debate speculative future risks", "platform": "twitter", "created_at": _ts(4), "like_count": 4800, "reply_count": 820, "retweet_count": 1600},

    # ── Diverse NBA views ─────────────────────────────────────
    {"text": "Analytics are ruining basketball by turning the sport into a three-point shooting contest with no artistry", "platform": "reddit", "created_at": _ts(1), "like_count": 7200, "reply_count": 1400, "retweet_count": 2300, "ups": 7200, "num_comments": 1400},
    {"text": "International players now dominate the NBA proving the global talent pool has overtaken USA domestic production", "platform": "twitter", "created_at": _ts(2), "like_count": 5400, "reply_count": 980, "retweet_count": 1800},
    {"text": "Player salaries have grown faster than ticket prices but average fans are still priced out of arena attendance", "platform": "twitter", "created_at": _ts(3), "like_count": 4100, "reply_count": 710, "retweet_count": 1300},
    {"text": "G League Ignite pathway allows top prospects to earn money while preparing for the NBA draft properly", "platform": "reddit", "created_at": _ts(2), "like_count": 2800, "reply_count": 450, "retweet_count": 890, "ups": 2800, "num_comments": 450},
    {"text": "European basketball leagues offer better player development paths than NBA bench roles for young talent", "platform": "twitter", "created_at": _ts(4), "like_count": 3600, "reply_count": 620, "retweet_count": 1100},
    {"text": "WNBA deserves equal coverage and investment instead of being treated as secondary to the mens league", "platform": "twitter", "created_at": _ts(1), "like_count": 9800, "reply_count": 1700, "retweet_count": 3500},

    # ── Diverse climate views ─────────────────────────────────
    {"text": "Climate policy is destroying jobs in rural communities while elites in cities virtue signal about sustainability", "platform": "twitter", "created_at": _ts(2), "like_count": 3400, "reply_count": 780, "retweet_count": 1200},
    {"text": "Nuclear power is the only realistic path to decarbonization at the scale and speed needed globally", "platform": "reddit", "created_at": _ts(1), "like_count": 4900, "reply_count": 920, "retweet_count": 1700, "ups": 4900, "num_comments": 920},
    {"text": "Developing nations have the right to use fossil fuels to grow their economies just as rich countries did", "platform": "twitter", "created_at": _ts(3), "like_count": 2800, "reply_count": 650, "retweet_count": 980},
    {"text": "Individual carbon footprints are a myth invented by BP to shift responsibility away from corporations", "platform": "reddit", "created_at": _ts(2), "like_count": 6700, "reply_count": 1100, "retweet_count": 2400, "ups": 6700, "num_comments": 1100},
    {"text": "Geoengineering research should be funded urgently as emissions cuts alone will not prevent dangerous warming", "platform": "twitter", "created_at": _ts(4), "like_count": 2200, "reply_count": 410, "retweet_count": 760},
    {"text": "Climate anxiety among young people is a public health crisis that requires systemic mental health support", "platform": "twitter", "created_at": _ts(1), "like_count": 5100, "reply_count": 890, "retweet_count": 1800},

    # ── Diverse music views ───────────────────────────────────
    {"text": "Music streaming has devalued songs to near zero making it impossible for mid-tier artists to survive financially", "platform": "reddit", "created_at": _ts(2), "like_count": 8900, "reply_count": 1600, "retweet_count": 3200, "ups": 8900, "num_comments": 1600},
    {"text": "AI generated music will democratize music production and allow non-musicians to express themselves creatively", "platform": "twitter", "created_at": _ts(1), "like_count": 3200, "reply_count": 690, "retweet_count": 1100},
    {"text": "Pop music has become increasingly formulaic with the same chord progressions and song structures repeated constantly", "platform": "twitter", "created_at": _ts(3), "like_count": 4600, "reply_count": 830, "retweet_count": 1600},
    {"text": "Ticketmaster monopoly on live music venues is the reason ticket prices have become completely unaffordable", "platform": "reddit", "created_at": _ts(2), "like_count": 12000, "reply_count": 2100, "retweet_count": 4600, "ups": 12000, "num_comments": 2100},
    {"text": "Music journalism is dead and algorithmic recommendation has replaced human curation of new artists entirely", "platform": "twitter", "created_at": _ts(4), "like_count": 2900, "reply_count": 510, "retweet_count": 980},
    {"text": "Social media virality now matters more than musical quality in determining which artists become successful", "platform": "twitter", "created_at": _ts(1), "like_count": 7100, "reply_count": 1200, "retweet_count": 2600},

    # ── Completely unrelated posts (should score low / be dropped) ──
    {"text": "Best recipe for homemade sourdough bread I have ever tried absolutely delicious highly recommend it", "platform": "reddit", "created_at": _ts(1), "like_count": 340, "reply_count": 45, "retweet_count": 90, "ups": 340, "num_comments": 45},
    {"text": "My cat knocked over the entire Christmas tree for the third time this December morning absolute disaster", "platform": "twitter", "created_at": _ts(2), "like_count": 8900, "reply_count": 1200, "retweet_count": 3100},
    {"text": "Traffic on the highway was completely terrible this morning due to an accident near the main interchange", "platform": "twitter", "created_at": _ts(1), "like_count": 120, "reply_count": 15, "retweet_count": 20},
    {"text": "Local farmers market opens for the spring season with fresh produce and artisan goods every Saturday", "platform": "reddit", "created_at": _ts(3), "like_count": 210, "reply_count": 28, "retweet_count": 45, "ups": 210, "num_comments": 28},
]

print(f"\n✓  Simulated search results: {len(SIMULATED_SEARCH_RESULTS)} posts")
print(f"   (represents K={K} queries × Q≈{len(SIMULATED_SEARCH_RESULTS)//K} posts each)")


# ──────────────────────────────────────────────────────────────
# CELL 8 ─ SECTION 3  ·  Cut-off  (Combined feed + search posts)
#           Separates into Balanced tab and Other tab
# ──────────────────────────────────────────────────────────────

print("\n" + "═" * 60)
print("  SECTION 3  ─  Diversity Cut-off")
print("═" * 60)

# Collect all keywords from Section 1 for relevance scoring
all_bubble_keywords = [kw for t in s1["topics"] for kw in t["keywords"]]

# Run Section 3 on SEARCH RESULTS only.
# (Following posts already went to Feed tab via Section 1.)
s3 = api.section3({
    "new_posts": SIMULATED_SEARCH_RESULTS,
    "bubble_keywords": all_bubble_keywords,
})

print(f"\n  Input posts    : {len(SIMULATED_SEARCH_RESULTS)}")
print(f"  Balanced (≥{BALANCED_THRESHOLD})  : {len(s3['balanced'])}  → feed back into Section 1 for Balanced tab")
print(f"  Other    (≥{MIN_DIVERSITY_SCORE})  : {len(s3['other'])}  → Other tab directly")
print(f"  Dropped  (<{MIN_DIVERSITY_SCORE})  : {s3['dropped']}")

print(f"\n  ── Balanced posts (top {min(8, len(s3['balanced']))}) ────────────────────────────")
for post, score in zip(s3["balanced"][:8], s3["balanced_scores"][:8]):
    print(f"  [{score:.2f}] [{post['platform']:7s}] {post['text'][:75]}")

print(f"\n  ── Other posts (top {min(5, len(s3['other']))}) ──────────────────────────────────")
for post, score in zip(s3["other"][:5], s3["other_scores"][:5]):
    print(f"  [{score:.2f}] [{post['platform']:7s}] {post['text'][:75]}")


# ──────────────────────────────────────────────────────────────
# CELL 9 ─ Feedback loop  ·  Run Section 1 on Balanced posts
#           (diagram: Balanced tab → Section 1 → Section 2 output)
# ──────────────────────────────────────────────────────────────

print("\n" + "═" * 60)
print("  BALANCED TAB  ─  Section 1 on Balanced Posts")
print("═" * 60)

if len(s3["balanced"]) >= 6:
    s1_balanced = api.section1(s3["balanced"])
    print(f"\n  Posts processed : {s1_balanced['total_posts_processed']}")
    print(f"  Topics found    : {len(s1_balanced['topics'])}")
    for t in s1_balanced["topics"]:
        print(f"\n  Topic {t['topic_id']}  [{t['category']}]  ({t['n_posts']} posts)")
        print(f"  Headline  : {t['headline'] or '(no summarizer)'}")
        print(f"  Keywords  : {', '.join(t['keywords'][:5])}")
        for rp in t["representative_posts"][:3]:
            print(f"    [{rp['platform']:7s}] {rp['text'][:70]}")
else:
    print(f"\n  ⚠  Only {len(s3['balanced'])} balanced posts — need ≥ 6 to re-cluster.")
    print("  Display balanced posts as a flat list instead:")
    for post, score in zip(s3["balanced"], s3["balanced_scores"]):
        print(f"    [{score:.2f}] {post['text'][:75]}")


# ──────────────────────────────────────────────────────────────
# CELL 10 ─ SECTION 2  ·  Full Summarization output display
#            (diagram: "Section 2: Summarization" block)
#            Shows what the frontend receives per topic.
# ──────────────────────────────────────────────────────────────

print("\n" + "═" * 60)
print("  SECTION 2  ─  Summarization output per topic")
print("  (Headline · Short Summary · Long Summary · Keywords)")
print("═" * 60)

for t in s1["topics"]:
    print(f"\n  ┌─ Topic {t['topic_id']}  [{t['category']}]  {t['n_posts']} posts")
    print(f"  │  Headline      : {t['headline']      or '(add summarizer for LLM headline)'}")
    print(f"  │  Short summary : {t['short_summary'] or '(add summarizer for short summary)'}")
    print(f"  │  Long summary  : {t['long_summary']  or '(add summarizer for long summary)'}")
    print(f"  │  Keywords      : {', '.join(t['keywords'][:8])}")
    print(f"  │  Key points    : {t['key_points'] or ['(add summarizer)']}")
    print(f"  └─ Rep. posts    : {len(t['representative_posts'])}")

print(f"\n  ── Digest (banner text) ────────────────────────────────")
print(f"  {s1['digest'] or '(add summarizer for LLM digest)'}")


# ──────────────────────────────────────────────────────────────
# CELL 11 ─ Summary table  (what each frontend tab receives)
# ──────────────────────────────────────────────────────────────

print("\n" + "═" * 60)
print("  FRONTEND OUTPUT SUMMARY")
print("═" * 60)
print(f"""
  ┌─────────────────────┬──────────────────────────────────────────────┐
  │  Tab                │  Content                                     │
  ├─────────────────────┼──────────────────────────────────────────────┤
  │  Feed & For You     │  {len(s1['topics'])} topics, {sum(len(t['representative_posts']) for t in s1['topics'])} rep. posts, digest banner   │
  │  Balanced           │  {len(s3['balanced'])} posts re-clustered into topics        │
  │  Other              │  {len(s3['other'])} posts shown as ranked flat list       │
  └─────────────────────┴──────────────────────────────────────────────┘

  Section 2A generated {len(s2['queries'])} search queries (sorted by diversity probability).
  Top query: {s2['queries'][0]['query_string'][:65] if s2['queries'] else 'n/a'}
""")

print("✓  Full flow test complete.")
